### ISSUE TITLE
Statistics shows nothing

### ISSUE THREAD

**Issue by Pardaigle** [Qowala/Qowala#19]
There is no statistics in the statistics section, even with a popular hashtag like #apple 
![capture](https://cloud.githubusercontent.com/assets/410235/6652077/5aedef52-cab5-11e4-9aaa-a3d6e27d4062.PNG)

**Comment by KillianKemps** [comment]
I'm unable to reproduce the bug.
As the screenshot shows, you don't have tweets in the search column. Even if you have a popular hashtag, it can happen you don't receive tweets during a certain amount of time.

Can you verify if you get tweets in the search column?
