### ISSUE TITLE
A click on an enlarged picture should open it in its original size

### ISSUE THREAD

**Issue by Pardaigle** [Qowala/Qowala#33]

**Comment by KillianKemps** [comment]
How should the original size image be opened? In a new tab? In a popup?

**Comment by Pardaigle** [comment]
Yeah in a popup like on twitter.com

I will make a mockup.

**Comment by Pardaigle** [comment]
![pictureenlarged](https://cloud.githubusercontent.com/assets/410235/7520404/c58eb88e-f529-11e4-99fd-fa690690380e.PNG)

In a popup (here: witdh 265px, height 519px) 
In the future we could adapt the zoom regarding the size of the source.
